# conda environment file for python 3, includes packages needed for testing
# and building the sphinx docs
# create a conda virtual env using:
#   conda env create -n myenv --file conda_environment.yml
#   source activate myenv (use 'activate myenv' on windows)
#   python setup.py develop
#
# optionally run tests:
#   python setup.py test

name: ulmo

channels:
    - conda-forge
    - defaults

dependencies:
    - python>=3.5
    - appdirs
    - beautifulsoup4
    - future
    - geojson
    - isodate
    - lxml
    - numpy
    - pandas
    - pytables
    - requests
    - suds-jurko

    # Specifically for building Sphinx docs
    - numpydoc>=0.4
    - python-dateutil
    - sphinx>=1.1.3

    # test dependencies
    - pip
    - coveralls
    - freezegun
    - html5lib
    - mock
    - pytest
    - pytest-cov
    - pytest-runner
    - httpretty
